#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

namespace grip {

/**
* RedMobileGoalPipeline class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class RedMobileGoalPipeline {
	private:
		cv::Mat rgbThresholdOutput;
		void rgbThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);

	public:
		RedMobileGoalPipeline();
		void Process(cv::Mat& source0);
		cv::Mat* GetRgbThresholdOutput();
};


} // end namespace grip


